//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace OliWorker
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OliWorkerContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OliWorkerContainer object using the connection string found in the 'OliWorkerContainer' section of the application configuration file.
        /// </summary>
        public OliWorkerContainer() : base("name=OliWorkerContainer", "OliWorkerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OliWorkerContainer object.
        /// </summary>
        public OliWorkerContainer(string connectionString) : base(connectionString, "OliWorkerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OliWorkerContainer object.
        /// </summary>
        public OliWorkerContainer(EntityConnection connection) : base(connection, "OliWorkerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WorkItem> WorkItem
        {
            get
            {
                if ((_WorkItem == null))
                {
                    _WorkItem = base.CreateObjectSet<WorkItem>("WorkItem");
                }
                return _WorkItem;
            }
        }
        private ObjectSet<WorkItem> _WorkItem;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WorkItem EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWorkItem(WorkItem workItem)
        {
            base.AddObject("WorkItem", workItem);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OliWorker", Name="WorkItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WorkItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WorkItem object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="created">Initial value of the created property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="imageurl">Initial value of the imageurl property.</param>
        public static WorkItem CreateWorkItem(global::System.Int32 id, global::System.DateTime created, global::System.String description, global::System.String imageurl)
        {
            WorkItem workItem = new WorkItem();
            workItem.Id = id;
            workItem.created = created;
            workItem.description = description;
            workItem.imageurl = imageurl;
            return workItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private global::System.DateTime _created;
        partial void OncreatedChanging(global::System.DateTime value);
        partial void OncreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String imageurl
        {
            get
            {
                return _imageurl;
            }
            set
            {
                OnimageurlChanging(value);
                ReportPropertyChanging("imageurl");
                _imageurl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("imageurl");
                OnimageurlChanged();
            }
        }
        private global::System.String _imageurl;
        partial void OnimageurlChanging(global::System.String value);
        partial void OnimageurlChanged();

        #endregion
    
    }

    #endregion
    
}
